
package com.spts.lms.sap.facultyWorkload;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ZFACULTY_WORKLOAD_WS", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "file:/data/wsdl/zfaculty_workload_bin_feq_02122019.wsdl")
public class ZFACULTYWORKLOADWS
    extends Service
{
    private final static URL ZFACULTYWORKLOADWS_WSDL_LOCATION;
    private final static WebServiceException ZFACULTYWORKLOADWS_EXCEPTION;
    private final static QName ZFACULTYWORKLOADWS_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZFACULTY_WORKLOAD_WS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
        	url = new URL("file:/data/wsdl/zfaculty_workload_bin_feq_02122019.wsdl"); 
//        	url = new URL("file:D:/wsdl/zfaculty_workload_bin_feq_02122019.wsdl"); 
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZFACULTYWORKLOADWS_WSDL_LOCATION = url;
        ZFACULTYWORKLOADWS_EXCEPTION = e;
    }

    public ZFACULTYWORKLOADWS() {
        super(__getWsdlLocation(), ZFACULTYWORKLOADWS_QNAME);
    }

    public ZFACULTYWORKLOADWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZFACULTYWORKLOADWS_QNAME, features);
    }

    public ZFACULTYWORKLOADWS(URL wsdlLocation) {
        super(wsdlLocation, ZFACULTYWORKLOADWS_QNAME);
    }

    public ZFACULTYWORKLOADWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZFACULTYWORKLOADWS_QNAME, features);
    }

    public ZFACULTYWORKLOADWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZFACULTYWORKLOADWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZfacultyWorkloadSd
     */
    @WebEndpoint(name = "ZFACULTY_WORKLOAD_BIN")
    public ZfacultyWorkloadSd getZFACULTYWORKLOADBIN() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZFACULTY_WORKLOAD_BIN"), ZfacultyWorkloadSd.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZfacultyWorkloadSd
     */
    @WebEndpoint(name = "ZFACULTY_WORKLOAD_BIN")
    public ZfacultyWorkloadSd getZFACULTYWORKLOADBIN(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZFACULTY_WORKLOAD_BIN"), ZfacultyWorkloadSd.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZFACULTYWORKLOADWS_EXCEPTION!= null) {
            throw ZFACULTYWORKLOADWS_EXCEPTION;
        }
        return ZFACULTYWORKLOADWS_WSDL_LOCATION;
    }

}
