
package com.spts.lms.sap.facultyWorkload;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "zfaculty_workload_sd", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZfacultyWorkloadSd {


    /**
     * 
     * @param ivEventid
     * @param ivDate
     * @param ivFacultyid
     * @return
     *     returns com.sap.document.sap.soap.functions.mc_style.ZfacultyworkloadTt
     */
    @WebMethod(operationName = "ZfacultyWorkload", action = "urn:sap-com:document:sap:soap:functions:mc-style:zfaculty_workload_sd:ZfacultyWorkloadRequest")
    @WebResult(name = "EtFacultyworkload", targetNamespace = "")
    @RequestWrapper(localName = "ZfacultyWorkload", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZfacultyWorkload")
    @ResponseWrapper(localName = "ZfacultyWorkloadResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZfacultyWorkloadResponse")
    public ZfacultyworkloadTt zfacultyWorkload(
        @WebParam(name = "IvDate", targetNamespace = "")
        String ivDate,
        @WebParam(name = "IvEventid", targetNamespace = "")
        String ivEventid,
        @WebParam(name = "IvFacultyid", targetNamespace = "")
        String ivFacultyid);

}
