
package com.spts.lms.studentms.sap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ZCHANGE_ST_MOBILE_EMAIL_WS_SEP", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "file:/F:/WSDL/zchange_st_mobile_email_bind_sep_sep_20200219.wsdl")
public class ZCHANGESTMOBILEEMAILWSSEP
    extends Service
{

    private final static URL ZCHANGESTMOBILEEMAILWSSEP_WSDL_LOCATION;
    private final static WebServiceException ZCHANGESTMOBILEEMAILWSSEP_EXCEPTION;
    private final static QName ZCHANGESTMOBILEEMAILWSSEP_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZCHANGE_ST_MOBILE_EMAIL_WS_SEP");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/data/wsdl/zchange_st_mobile_email_bind_sep_sep_20200219.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZCHANGESTMOBILEEMAILWSSEP_WSDL_LOCATION = url;
        ZCHANGESTMOBILEEMAILWSSEP_EXCEPTION = e;
    }

    public ZCHANGESTMOBILEEMAILWSSEP() {
        super(__getWsdlLocation(), ZCHANGESTMOBILEEMAILWSSEP_QNAME);
    }

    public ZCHANGESTMOBILEEMAILWSSEP(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZCHANGESTMOBILEEMAILWSSEP_QNAME, features);
    }

    public ZCHANGESTMOBILEEMAILWSSEP(URL wsdlLocation) {
        super(wsdlLocation, ZCHANGESTMOBILEEMAILWSSEP_QNAME);
    }

    public ZCHANGESTMOBILEEMAILWSSEP(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZCHANGESTMOBILEEMAILWSSEP_QNAME, features);
    }

    public ZCHANGESTMOBILEEMAILWSSEP(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZCHANGESTMOBILEEMAILWSSEP(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZCHANGESTMOBILEEMAILWSD
     */
    @WebEndpoint(name = "ZCHANGE_ST_MOBILE_EMAIL_BIND_SEP")
    public ZCHANGESTMOBILEEMAILWSD getZCHANGESTMOBILEEMAILBINDSEP() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZCHANGE_ST_MOBILE_EMAIL_BIND_SEP"), ZCHANGESTMOBILEEMAILWSD.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZCHANGESTMOBILEEMAILWSD
     */
    @WebEndpoint(name = "ZCHANGE_ST_MOBILE_EMAIL_BIND_SEP")
    public ZCHANGESTMOBILEEMAILWSD getZCHANGESTMOBILEEMAILBINDSEP(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZCHANGE_ST_MOBILE_EMAIL_BIND_SEP"), ZCHANGESTMOBILEEMAILWSD.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZCHANGESTMOBILEEMAILWSSEP_EXCEPTION!= null) {
            throw ZCHANGESTMOBILEEMAILWSSEP_EXCEPTION;
        }
        return ZCHANGESTMOBILEEMAILWSSEP_WSDL_LOCATION;
    }

}
