
package com.spts.lms.studentms.sap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ZCHANGE_ST_MOBILE_EMAIL_WSD_FEQ", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "file:/D:/Tejas/AfterCovid/Java%20Portal-FEQ300/zchange_st_mobile_email_bind_feq.WSDL")
public class ZCHANGESTMOBILEEMAILWSDFEQ
    extends Service
{

    private final static URL ZCHANGESTMOBILEEMAILWSDFEQ_WSDL_LOCATION;
    private final static WebServiceException ZCHANGESTMOBILEEMAILWSDFEQ_EXCEPTION;
    private final static QName ZCHANGESTMOBILEEMAILWSDFEQ_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZCHANGE_ST_MOBILE_EMAIL_WSD_FEQ");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/Tejas/AfterCovid/Java%20Portal-FEQ300/zchange_st_mobile_email_bind_feq.WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZCHANGESTMOBILEEMAILWSDFEQ_WSDL_LOCATION = url;
        ZCHANGESTMOBILEEMAILWSDFEQ_EXCEPTION = e;
    }

    public ZCHANGESTMOBILEEMAILWSDFEQ() {
        super(__getWsdlLocation(), ZCHANGESTMOBILEEMAILWSDFEQ_QNAME);
    }

    public ZCHANGESTMOBILEEMAILWSDFEQ(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZCHANGESTMOBILEEMAILWSDFEQ_QNAME, features);
    }

    public ZCHANGESTMOBILEEMAILWSDFEQ(URL wsdlLocation) {
        super(wsdlLocation, ZCHANGESTMOBILEEMAILWSDFEQ_QNAME);
    }

    public ZCHANGESTMOBILEEMAILWSDFEQ(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZCHANGESTMOBILEEMAILWSDFEQ_QNAME, features);
    }

    public ZCHANGESTMOBILEEMAILWSDFEQ(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZCHANGESTMOBILEEMAILWSDFEQ(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZCHANGESTMOBILEEMAILWSD
     */
    @WebEndpoint(name = "ZCHANGE_ST_MOBILE_EMAIL_BIND_FEQ")
    public ZCHANGESTMOBILEEMAILWSD getZCHANGESTMOBILEEMAILBINDFEQ() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZCHANGE_ST_MOBILE_EMAIL_BIND_FEQ"), ZCHANGESTMOBILEEMAILWSD.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZCHANGESTMOBILEEMAILWSD
     */
    @WebEndpoint(name = "ZCHANGE_ST_MOBILE_EMAIL_BIND_FEQ")
    public ZCHANGESTMOBILEEMAILWSD getZCHANGESTMOBILEEMAILBINDFEQ(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZCHANGE_ST_MOBILE_EMAIL_BIND_FEQ"), ZCHANGESTMOBILEEMAILWSD.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZCHANGESTMOBILEEMAILWSDFEQ_EXCEPTION!= null) {
            throw ZCHANGESTMOBILEEMAILWSDFEQ_EXCEPTION;
        }
        return ZCHANGESTMOBILEEMAILWSDFEQ_WSDL_LOCATION;
    }

}
