
package com.spts.lms.studentms.sap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ZCHANGE_ST_MOBILE_EMAIL_WSD", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZCHANGESTMOBILEEMAILWSD {


    /**
     * 
     * @param stobjid
     * @param tMessage
     * @param photo
     * @param emailId
     * @param mobileNo
     * @param stnum
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ZchangeStMobileEmail", action = "urn:sap-com:document:sap:soap:functions:mc-style:ZCHANGE_ST_MOBILE_EMAIL_WSD:ZchangeStMobileEmailRequest")
    @WebResult(name = "Return", targetNamespace = "")
    @RequestWrapper(localName = "ZchangeStMobileEmail", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZchangeStMobileEmail")
    @ResponseWrapper(localName = "ZchangeStMobileEmailResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZchangeStMobileEmailResponse")
    public String zchangeStMobileEmail(
        @WebParam(name = "EmailId", targetNamespace = "")
        String emailId,
        @WebParam(name = "MobileNo", targetNamespace = "")
        String mobileNo,
        @WebParam(name = "Photo", targetNamespace = "")
        String photo,
        @WebParam(name = "Stnum", targetNamespace = "")
        String stnum,
        @WebParam(name = "Stobjid", targetNamespace = "")
        String stobjid,
        @WebParam(name = "TMessage", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ZmessageLogTt> tMessage);

}
