
package com.spts.lms.sap.attendance;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ZATT_ST_PORTAL_UPDATE_WS", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "file:/data/wsdl/zatt_st_portal_update_bin.WSDL")
public class ZATTSTPORTALUPDATEWS
    extends Service
{

    private final static URL ZATTSTPORTALUPDATEWS_WSDL_LOCATION;
    private final static WebServiceException ZATTSTPORTALUPDATEWS_EXCEPTION;
    private final static QName ZATTSTPORTALUPDATEWS_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZATT_ST_PORTAL_UPDATE_WS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
//            url = new URL("file:/C:/Users/ASUS/Downloads/Student%20Attendance%20WSDL/zatt_st_portal_update_bin.WSDL");
        	 url = new URL("file:/data/wsdl/zatt_st_portal_update_bin.WSDL");
            
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZATTSTPORTALUPDATEWS_WSDL_LOCATION = url;
        ZATTSTPORTALUPDATEWS_EXCEPTION = e;
    }

    public ZATTSTPORTALUPDATEWS() {
        super(__getWsdlLocation(), ZATTSTPORTALUPDATEWS_QNAME);
    }

    public ZATTSTPORTALUPDATEWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZATTSTPORTALUPDATEWS_QNAME, features);
    }

    public ZATTSTPORTALUPDATEWS(URL wsdlLocation) {
        super(wsdlLocation, ZATTSTPORTALUPDATEWS_QNAME);
    }

    public ZATTSTPORTALUPDATEWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZATTSTPORTALUPDATEWS_QNAME, features);
    }

    public ZATTSTPORTALUPDATEWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZATTSTPORTALUPDATEWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZATTSTPORTALUPDATESD
     */
    @WebEndpoint(name = "ZATT_ST_PORTAL_UPDATE_BIN")
    public ZATTSTPORTALUPDATESD getZATTSTPORTALUPDATEBIN() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZATT_ST_PORTAL_UPDATE_BIN"), ZATTSTPORTALUPDATESD.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZATTSTPORTALUPDATESD
     */
    @WebEndpoint(name = "ZATT_ST_PORTAL_UPDATE_BIN")
    public ZATTSTPORTALUPDATESD getZATTSTPORTALUPDATEBIN(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZATT_ST_PORTAL_UPDATE_BIN"), ZATTSTPORTALUPDATESD.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZATTSTPORTALUPDATEWS_EXCEPTION!= null) {
            throw ZATTSTPORTALUPDATEWS_EXCEPTION;
        }
        return ZATTSTPORTALUPDATEWS_WSDL_LOCATION;
    }

}
