
package com.spts.lms.sap.attendance;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ZATT_ST_PORTAL_UPDATE_SD", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZATTSTPORTALUPDATESD {


    /**
     * 
     * @param itAttSt
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ZattStPortalUpdate", action = "urn:sap-com:document:sap:soap:functions:mc-style:ZATT_ST_PORTAL_UPDATE_SD:ZattStPortalUpdateRequest")
    @WebResult(name = "Return", targetNamespace = "")
    @RequestWrapper(localName = "ZattStPortalUpdate", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZattStPortalUpdate")
    @ResponseWrapper(localName = "ZattStPortalUpdateResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZattStPortalUpdateResponse")
    public String zattStPortalUpdate(
        @WebParam(name = "ItAttSt", targetNamespace = "")
        ZattStPortalTt itAttSt);

}
